---
- name: Update apt
  apt: update_cache=yes cache_valid_time=7200

- name: Upgrade all pkgs
  apt: upgrade=yes

- name: Install common progs/libs
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libreadline-dev
    - git
    - ack-grep
    - curl

