---
- name: Update apt
  apt: update_cache=yes cache_valid_time=7200

- name: Upgrade all pkgs
  apt: upgrade=yes

- name: Install common progs/libs
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libreadline-dev
    - git
    - ack-grep
    - curl

- name: Create deploy user
  user: name={{ user }} shell=/bin/bash

- name: Copy rc to profile.d
  copy: src=custom.sh dest=/etc/profile.d/custom.sh

- name: Create apps dir
  file: path=/apps owner={{ user }} group={{ user }} state=directory

- name: Create .ssh dir
  file: path={{ home_path }}/.ssh owner={{ user }} group={{ user }} state=directory

- name: Copy public key to authorized keys
  copy: src={{ local_home_path }}/.ssh/id_rsa.pub dest={{ home_path }}/.ssh/authorized_keys owner={{ user }} group={{ user }}

