---
- name: Check iojs executable exists
  shell: test -x /usr/local/bin/iojs
  register: iojs_exists
  ignore_errors: yes

- name: Download tarball
  when: iojs_exists|failed
  get_url: url=https://iojs.org/dist/latest/{{ iojs_tarball }} dest=/tmp
  register: iojs_downloaded

- name: Extract tarball
  when: iojs_downloaded|changed
  unarchive: src=/tmp/{{ iojs_tarball }} dest=/tmp copy=no
  register: iojs_extracted

- name: Move to target
  when: iojs_extracted|changed
  shell: "mv /tmp/{{ iojs_package }} {{ iojs_path }}"

- name: Link binaries
  remote_user: root
  file: src={{ iojs_path }}/bin/{{ item }} dest=/usr/local/bin/{{ item }} state=link
  with_items:
    - iojs
    - npm
    - node

