# https://github.com/sstephenson/ruby-build/issues/690#issuecomment-68113987
- name: Install deps
  remote_user: root
  apt: pkg={{ item }} state=present
  with_items:
    - libffi-dev
    - zlib1g-dev
    - libssl-dev
    - libpq-dev

- name: Install ruby with ruby-build
  shell: rbenv install --skip-existing {{ ruby_version }}

- name: Set global ruby
  shell: rbenv global {{ ruby_version }}
 
- name: Add gemrc
  copy: src=gemrc dest=/home/{{ user }}/.gemrc

- name: Install bundler
  gem: name=bundler state=present

- name: Rehash rbenv
  shell: rbenv rehash

